# Use root/example as user/password credentials
version: '3.1'

services:

  L2jToren:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 9643
      MARIADB_USER: L2jToren
      MARIADB_PASSWORD: 9643
    ports:
      - "3306:3306"
    volumes:
      - ./L2jTorenTest/L2jTorenDB:/var/lib/mysql