CREATE TABLE IF NOT EXISTS vip_system (
    `char_id` INT UNSIGNED NOT NULL,
    `vip_level` INT NOT NULL DEFAULT 0,
    `vip_exp` BIGINT UNSIGNED NOT NULL DEFAULT 0,
    `vip_time` BIGINT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (`char_id`)
);
